=== ShurayukiHime/StickyPolicies/StickyPolicies/PKIstickypolicy.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="stickyPolicy" type="stickyPolicyType" />

	<xs:complexType name="stickyPolicyType">
		<xs:sequence>
			<xs:element name="trustedAuthority" type="xs:string" maxOccurs="unbounded" minOccurs="1" />
			<xs:element name="owner" type="ownerType" maxOccurs="1" minOccurs="1" />
			<xs:element name="policy" type="policyType" maxOccurs="unbounded" minOccurs="1" />
	</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="policyType">
		<xs:sequence>
			<xs:element name="target" type="xs:string" maxOccurs="unbounded" minOccurs="1" />
			<xs:element name="dataType" type="dataType" maxOccurs="unbounded" minOccurs="1" />
			<xs:element name="validity" type="dateType" maxOccurs="1" minOccurs="1" />
			<xs:element name="constraint" type="xs:string" maxOccurs="unbounded" minOccurs="1" />
			<xs:element name="action" type="xs:string" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ownerType">
		<xs:sequence>
			<xs:element name="referenceName" type="xs:string" maxOccurs="1" minOccurs="1"  />
			<xs:element name="ownersDetails" type="xs:string" maxOccurs="unbounded" minOccurs="1"  />
			<xs:element name="certificateSerialNumber" type="xs:unsignedLong" maxOccurs="1" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="dataType" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="picture" />
			<xs:enumeration value="text" />
			<xs:enumeration value="video" />
			<xs:enumeration value="audio" />
			<xs:enumeration value="position" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="dateType">
		<xs:sequence>
			<xs:element name="day" type="dayType" />
			<xs:element name="month" type="monthType" />
			<xs:element name="year" type="yearType" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="dayType" >
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="31" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="monthType" >
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="12" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="yearType" >
			<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="2017" />
			<xs:maxInclusive value="2027" />
			</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ShurayukiHime/StickyPolicies/StickyPolicies/policy2.xml
<?xml version="1.0" encoding="UTF-8"?>
<stickyPolicy xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="PKIstickypolicy.xsd">

    <trustedAuthority>trustedAuthority1</trustedAuthority>

   <owner>
        <referenceName>referenceName1</referenceName>
        <ownersDetails>ownersDetails1</ownersDetails>
        <ownersDetails>ownersDetails2</ownersDetails>
        <certificateSerialNumber>6098596622719104000</certificateSerialNumber>
    </owner>

   <policy>
        <target>target1</target>
        <target>target2</target>
        <dataType>text</dataType>
        <dataType>audio</dataType>
        <validity>
            <day>2</day>
            <month>5</month>
            <year>2023</year>
        </validity>
        <constraint>constraint1</constraint>
        <action>action1</action>
        <action>action2</action>
    </policy>

   <policy>
        <target>target3</target>
        <target>target4</target>
        <dataType>video</dataType>
        <validity>
            <day>17</day>
            <month>3</month>
            <year>2027</year>
        </validity>
        <constraint>constraint2</constraint>
        <constraint>constraint3</constraint>
        <action>action3</action>
    </policy>
</stickyPolicy>

=== ShurayukiHime/StickyPolicies/server/PolicyServer/policy3.xml
<?xml version="1.0" encoding="UTF-8"?>
<stickyPolicy xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="PKIstickypolicy.xsd">

    <trustedAuthority>trustedAuthority1</trustedAuthority>
    <trustedAuthority>trustedAuthority2</trustedAuthority>

   <owner>
        <referenceName>referenceName1</referenceName>
        <ownersDetails>ownersDetails1</ownersDetails>
        <ownersDetails>ownersDetails2</ownersDetails>
    </owner>

   <policy>
        <target>target1</target>
        <target>target2</target>
        <dataType>picture</dataType>
        <validity>
            <day>12</day>
            <month>10</month>
            <year>2020</year>
        </validity>
        <constraint>constraint1</constraint>
        <constraint>constraint2</constraint>
        <action>action1</action>
    </policy>

   <policy>
        <target>target3</target>
        <target>target4</target>
        <dataType>audio</dataType>
        <dataType>position</dataType>
        <validity>
            <day>21</day>
            <month>4</month>
            <year>2021</year>
        </validity>
        <constraint>constraint3</constraint>
        <action>action2</action>
        <action>action3</action>
    </policy>
</stickyPolicy>
