=== ShurayukiHime/StickyPolicies/server/PolicyServer/PKIstickypolicy.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="stickyPolicy" type="stickyPolicyType" />

	<xs:complexType name="stickyPolicyType">
		<xs:sequence>
			<xs:element name="dataPackage" type="dataPackageType" maxOccurs="unbounded" minOccurs="1"/>
	</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="dataPackageType">
		<xs:sequence>
			<xs:element name="pkiPolicy" type="pkiPolicyType" maxOccurs="1" minOccurs="1"/>
			<xs:element name="encryptedData" type="xs:string" maxOccurs="1" minOccurs="1" />
	</xs:sequence>
	</xs:complexType>

	<xs:complexType name="pkiPolicyType">
		<xs:sequence>
			<xs:element name="trustedAuthority" type="xs:string" maxOccurs="unbounded" minOccurs="1" />
			<xs:element name="owner" type="ownerType" maxOccurs="1" minOccurs="1" />
			<xs:element name="policy" type="policyType" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="policyType">
		<xs:sequence>
			<xs:element name="target" type="xs:string" maxOccurs="unbounded" minOccurs="1" />
			<xs:element name="validity" type="dataType" maxOccurs="1" minOccurs="1" />
			<xs:element name="constraint" type="xs:string" maxOccurs="unbounded" minOccurs="1" />
			<xs:element name="action" type="xs:string" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ownerType">
		<xs:sequence>
			<xs:element name="referenceName" type="xs:string" maxOccurs="1" minOccurs="1"  />
			<xs:element name="ownersDetails" type="xs:string" maxOccurs="unbounded" minOccurs="1"  />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="dataType">
		<xs:sequence>
			<xs:element name="giorno" type="giornoType" />
			<xs:element name="mese" type="meseType" />
			<xs:element name="anno" type="annoType" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="giornoType" >
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="31" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="meseType" >
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="12" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="annoType" >
			<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="2017" />
			<xs:maxInclusive value="2027" />
			</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ShurayukiHime/StickyPolicies/server/PolicyServer/policy2.xml
<?xml version="1.0" encoding="UTF-8"?>
<stickyPolicy xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="PKIstickypolicy.xsd">

    <dataPackage>

      <pkiPolicy>
            <trustedAuthority>trustedAuthority1</trustedAuthority>

         <owner>
                <referenceName>referenceName1</referenceName>
                <ownersDetails>ownersDetails1</ownersDetails>
                <ownersDetails>ownersDetails2</ownersDetails>
            </owner>

         <policy>
                <target>target1</target>
                <target>target2</target>
                <validity>
                    <giorno>17</giorno>
                    <mese>9</mese>
                    <anno>2025</anno>
                </validity>
                <constraint>constraint1</constraint>
                <constraint>constraint2</constraint>
                <action>action1</action>
            </policy>

         <policy>
                <target>target3</target>
                <validity>
                    <giorno>6</giorno>
                    <mese>11</mese>
                    <anno>2024</anno>
                </validity>
                <constraint>constraint3</constraint>
                <constraint>constraint4</constraint>
                <action>action2</action>
                <action>action3</action>
            </policy>
        </pkiPolicy>
        <encryptedData>encryptedData1</encryptedData>
    </dataPackage>
    <dataPackage>

      <pkiPolicy>
            <trustedAuthority>trustedAuthority2</trustedAuthority>
            <trustedAuthority>trustedAuthority3</trustedAuthority>

         <owner>
                <referenceName>referenceName2</referenceName>
                <ownersDetails>ownersDetails3</ownersDetails>
                <ownersDetails>ownersDetails4</ownersDetails>
            </owner>

         <policy>
                <target>target4</target>
                <target>target5</target>
                <validity>
                    <giorno>23</giorno>
                    <mese>8</mese>
                    <anno>2021</anno>
                </validity>
                <constraint>constraint5</constraint>
                <action>action4</action>
            </policy>

         <policy>
                <target>target6</target>
                <validity>
                    <giorno>25</giorno>
                    <mese>5</mese>
                    <anno>2020</anno>
                </validity>
                <constraint>constraint6</constraint>
                <constraint>constraint7</constraint>
                <action>action5</action>
                <action>action6</action>
            </policy>
        </pkiPolicy>
        <encryptedData>encryptedData2</encryptedData>
    </dataPackage>
</stickyPolicy>

=== ShurayukiHime/StickyPolicies/server/PolicyServer/policy1.xml
<?xml version="1.0"?>
<stickyPolicy xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="PKIstickypolicy.xsd">
	<dataPackage>
			<pkiPolicy> 
				<trustedAuthority> 
					address and location of the Trusted Authority 
				</trustedAuthority> 
				<owner> 
					<referenceName> pseudonym1 </referenceName>
					<ownersDetails>  encrypted call back address</ownersDetails>
				</owner> 
				<policy>
					<target> name of the identity or profile attribute</target> 
					<validity> 
						<giorno>07</giorno>
                    	<mese>12</mese>
                    	<anno>2022</anno>
					</validity> 
					<constraint>require_strong_X.509_authentication</constraint> 
					<constraint> allow_sharing_of_data </constraint> 
					<action>notify_owner </action>
				</policy>
			</pkiPolicy> 
			<encryptedData> encrypted attribute value, using the above policy as IBE public key</encryptedData> 
	</dataPackage>
</stickyPolicy>
